/**
 * Runs inside Expensify/App's own Jest setup (copied there by `refresh.sh`) and writes the parts of the
 * App that the suite mirrors into `perf-suite/app/generated/`: the full `ONYXKEYS`, the `CONST` subtrees
 * the fixtures and init options read, and the dependency list of every derived value.
 */
import fs from 'fs';
import path from 'path';

import ONYX_DERIVED_VALUES from '@libs/actions/OnyxDerived/ONYX_DERIVED_VALUES';

import CONST from '@src/CONST';
import ONYXKEYS from '@src/ONYXKEYS';

const PICKED_CONST = {
    DEFAULT_ACCOUNT_DATA: CONST.DEFAULT_ACCOUNT_DATA,
    SKIPPABLE_COLLECTION_MEMBER_IDS: CONST.SKIPPABLE_COLLECTION_MEMBER_IDS,
    LOCALES: CONST.LOCALES,
    REPORT: {
        ACTIONS: {TYPE: CONST.REPORT.ACTIONS.TYPE},
        CHAT_TYPE: CONST.REPORT.CHAT_TYPE,
        TYPE: CONST.REPORT.TYPE,
        MESSAGE: {TYPE: CONST.REPORT.MESSAGE.TYPE},
    },
    POLICY: {
        APPROVAL_MODE: CONST.POLICY.APPROVAL_MODE,
        AUTO_REPORTING_FREQUENCIES: CONST.POLICY.AUTO_REPORTING_FREQUENCIES,
        ROLE: CONST.POLICY.ROLE,
        TYPE: CONST.POLICY.TYPE,
    },
    RED_BRICK_ROAD_PENDING_ACTION: CONST.RED_BRICK_ROAD_PENDING_ACTION,
    CURRENCY: CONST.CURRENCY,
    CUSTOM_UNITS: {
        DISTANCE_UNIT_MILES: CONST.CUSTOM_UNITS.DISTANCE_UNIT_MILES,
        NAME_DISTANCE: CONST.CUSTOM_UNITS.NAME_DISTANCE,
    },
    DATE: {FNS_DB_FORMAT_STRING: CONST.DATE.FNS_DB_FORMAT_STRING},
    IOU: {REQUEST_TYPE: CONST.IOU.REQUEST_TYPE},
    TRANSACTION: {STATUS: CONST.TRANSACTION.STATUS, TYPE: CONST.TRANSACTION.TYPE},
    SEARCH: {
        DATA_TYPES: CONST.SEARCH.DATA_TYPES,
        SORT_ORDER: CONST.SEARCH.SORT_ORDER,
        TABLE_COLUMNS: CONST.SEARCH.TABLE_COLUMNS,
        SNAPSHOT_ONYX_KEYS: CONST.SEARCH.SNAPSHOT_ONYX_KEYS,
    },
};

function toModule(source: string, name: string, value: unknown): string {
    return [
        '// Generated by perf-suite/app/snapshot/refresh.sh. Do not edit by hand.',
        `// Source: Expensify/App ${source}`,
        `const ${name} = ${JSON.stringify(value, null, 4)} as const;`,
        '',
        `export default ${name};`,
        '',
    ].join('\n');
}

test('writes the App model snapshot', () => {
    const outDir = process.env.PERF_SUITE_SNAPSHOT_DIR;
    const source = process.env.PERF_SUITE_SNAPSHOT_SOURCE ?? 'unknown';

    if (!outDir) {
        throw new Error('PERF_SUITE_SNAPSHOT_DIR is not set; run perf-suite/app/snapshot/refresh.sh.');
    }

    const derived = Object.entries(ONYX_DERIVED_VALUES).map(([key, config]) => ({key, dependencies: config.dependencies}));

    fs.writeFileSync(path.join(outDir, 'ONYXKEYS.ts'), toModule(source, 'ONYXKEYS', ONYXKEYS));
    fs.writeFileSync(path.join(outDir, 'CONST.ts'), toModule(source, 'CONST', PICKED_CONST));
    fs.writeFileSync(path.join(outDir, 'DERIVED_DEPENDENCIES.ts'), toModule(source, 'DERIVED_DEPENDENCIES', derived));
});
